<?php
//////////////////////////////////////// Register Messages Post Type
function message_post_type() {
	$labels = array(
		'name'                  => _x( 'Messages', 'Post Type General Name', 'rockharbor' ),
		'singular_name'         => _x( 'Message', 'Post Type Singular Name', 'rockharbor' ),
		'menu_name'             => __( 'Messages', 'rockharbor' ),
		'name_admin_bar'        => __( 'Messages', 'rockharbor' ),
		'archives'              => __( 'Message Archives', 'rockharbor' ),
		'attributes'            => __( 'Message Attributes', 'rockharbor' ),
		'parent_item_colon'     => __( 'Parent Message:', 'rockharbor' ),
		'all_items'             => __( 'All Messages', 'rockharbor' ),
		'add_new_item'          => __( 'Add New Message', 'rockharbor' ),
		'add_new'               => __( 'Add New', 'rockharbor' ),
		'new_item'              => __( 'New Message', 'rockharbor' ),
		'edit_item'             => __( 'Edit Message', 'rockharbor' ),
		'update_item'           => __( 'Update Message', 'rockharbor' ),
		'view_item'             => __( 'View Message', 'rockharbor' ),
		'view_items'            => __( 'View Message', 'rockharbor' ),
		'search_items'          => __( 'Search Message', 'rockharbor' ),
		'not_found'             => __( 'Not found', 'rockharbor' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'rockharbor' ),
		'featured_image'        => __( 'Featured Image', 'rockharbor' ),
		'set_featured_image'    => __( 'Set featured image', 'rockharbor' ),
		'remove_featured_image' => __( 'Remove featured image', 'rockharbor' ),
		'use_featured_image'    => __( 'Use as featured image', 'rockharbor' ),
		'insert_into_item'      => __( 'Insert into message', 'rockharbor' ),
		'uploaded_to_this_item' => __( 'Uploaded to this message', 'rockharbor' ),
		'items_list'            => __( 'Message list', 'rockharbor' ),
		'items_list_navigation' => __( 'Message list navigation', 'rockharbor' ),
		'filter_items_list'     => __( 'Filter message list', 'rockharbor' ),
	);
	$args = array(
		'label'                 => __( 'Message', 'rockharbor' ),
		'description'           => __( 'Messages information page.', 'rockharbor' ),
		'labels'                => $labels,
		'supports'              => array( 'title', 'editor', 'thumbnail', 'excerpt', 'revisions' ),
		'taxonomies' 			=> array( 'series', 'teacher', 'campuses', 'tags' ),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'menu_icon'             => 'dashicons-video-alt3',
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => false,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
        'rewrite' => array('with_front' => false, 'slug' => 'message'),
	);
	register_post_type( 'message', $args );
}
add_action( 'init', 'message_post_type', 0 );

//////////////////////////////////////// Register Campus Post Type
function campus_post_type() {
	$labels = array(
		'name'                  => _x( 'Campuses', 'Post Type General Name', 'rockharbor' ),
		'singular_name'         => _x( 'Campus', 'Post Type Singular Name', 'rockharbor' ),
		'menu_name'             => __( 'Campuses', 'rockharbor' ),
		'name_admin_bar'        => __( 'Campus', 'rockharbor' ),
		'archives'              => __( 'Campus Archives', 'rockharbor' ),
		'attributes'            => __( 'Campus Attributes', 'rockharbor' ),
		'parent_item_colon'     => __( 'Parent Campus:', 'rockharbor' ),
		'all_items'             => __( 'All Campuses', 'rockharbor' ),
		'add_new_item'          => __( 'Add New Campus', 'rockharbor' ),
		'add_new'               => __( 'Add New', 'rockharbor' ),
		'new_item'              => __( 'New Campus', 'rockharbor' ),
		'edit_item'             => __( 'Edit Campus', 'rockharbor' ),
		'update_item'           => __( 'Update Campus', 'rockharbor' ),
		'view_item'             => __( 'View Campus', 'rockharbor' ),
		'view_items'            => __( 'View Campuses', 'rockharbor' ),
		'search_items'          => __( 'Search Campus', 'rockharbor' ),
		'not_found'             => __( 'Not found', 'rockharbor' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'rockharbor' ),
		'featured_image'        => __( 'Featured Image', 'rockharbor' ),
		'set_featured_image'    => __( 'Set featured image', 'rockharbor' ),
		'remove_featured_image' => __( 'Remove featured image', 'rockharbor' ),
		'use_featured_image'    => __( 'Use as featured image', 'rockharbor' ),
		'insert_into_item'      => __( 'Insert into campus', 'rockharbor' ),
		'uploaded_to_this_item' => __( 'Uploaded to this campus', 'rockharbor' ),
		'items_list'            => __( 'Campuses list', 'rockharbor' ),
		'items_list_navigation' => __( 'Campuses list navigation', 'rockharbor' ),
		'filter_items_list'     => __( 'Filter campuses list', 'rockharbor' ),
	);
	$args = array(
		'label'                 => __( 'Campus', 'rockharbor' ),
		'description'           => __( 'Church Campus information page.', 'rockharbor' ),
		'labels'                => $labels,
		'supports'              => array( 'title', 'editor', 'thumbnail', 'page-attributes', 'revisions' ),
		//'taxonomies'            => array( 'region', 'city' ),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'menu_icon'             => 'dashicons-admin-multisite',
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => false,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
        'rewrite' => array('with_front' => false, 'slug' => 'campus'),
	);
	register_post_type( 'campus', $args );
}
add_action( 'init', 'campus_post_type', 0 );

//////////////////////////////////////// Register Custom Post Type
function staff_post_type() {
	$labels = array(
		'name'                  => _x( 'Staff', 'Post Type General Name', 'rockharbor' ),
		'singular_name'         => _x( 'Staff', 'Post Type Singular Name', 'rockharbor' ),
		'menu_name'             => __( 'Staff', 'rockharbor' ),
		'name_admin_bar'        => __( 'Staff', 'rockharbor' ),
		'archives'              => __( 'Staff Archives', 'rockharbor' ),
		'attributes'            => __( 'Staff Attributes', 'rockharbor' ),
		'parent_item_colon'     => __( 'Parent Staff:', 'rockharbor' ),
		'all_items'             => __( 'All Staff', 'rockharbor' ),
		'add_new_item'          => __( 'Add New Staff', 'rockharbor' ),
		'add_new'               => __( 'Add New', 'rockharbor' ),
		'new_item'              => __( 'New Staff', 'rockharbor' ),
		'edit_item'             => __( 'Edit Staff', 'rockharbor' ),
		'update_item'           => __( 'Update Staff', 'rockharbor' ),
		'view_item'             => __( 'View Staff', 'rockharbor' ),
		'view_items'            => __( 'View Staff', 'rockharbor' ),
		'search_items'          => __( 'Search Staff', 'rockharbor' ),
		'not_found'             => __( 'Not found', 'rockharbor' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'rockharbor' ),
		'featured_image'        => __( 'Featured Image', 'rockharbor' ),
		'set_featured_image'    => __( 'Set featured image', 'rockharbor' ),
		'remove_featured_image' => __( 'Remove featured image', 'rockharbor' ),
		'use_featured_image'    => __( 'Use as featured image', 'rockharbor' ),
		'insert_into_item'      => __( 'Insert into staff', 'rockharbor' ),
		'uploaded_to_this_item' => __( 'Uploaded to this staff', 'rockharbor' ),
		'items_list'            => __( 'Staff list', 'rockharbor' ),
		'items_list_navigation' => __( 'Staff list navigation', 'rockharbor' ),
		'filter_items_list'     => __( 'Filter staff list', 'rockharbor' ),
	);
	$args = array(
		'label'                 => __( 'Staff', 'rockharbor' ),
		'description'           => __( 'Staff information page.', 'rockharbor' ),
		'labels'                => $labels,
		'supports'              => array( 'title', 'editor', 'thumbnail', 'revisions' ),
        //'taxonomies'            => array( 'region', 'city' ),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'menu_icon'             => 'dashicons-nametag',
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => false,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
        'rewrite' => array('with_front' => false, 'slug' => 'staff'),
	);
	register_post_type( 'staff', $args );
}
add_action( 'init', 'staff_post_type', 0 );
